In [1]:
import pandas as  pd

In [3]:
df =pd.read_csv("indian_roads_dataset.csv")

In [5]:
df.head()

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10

In [7]:
df.shape

(20000, 24)

In [8]:
df[["date","time"]].head(10)

         date   time
0  2023-10-22   5:00
1  2023-05-21   4:00
2  2024-07-10  13:00
3  2025-03-30  11:00
4  2024-01-25  16:00
5  2024-07-29   8:00
6  2025-03-24   6:00
7  2023-05-07  14:00
8  2022-02-25   3:00
9  2024-03-31   4:00

In [13]:
df.shape

(20000, 22)

In [14]:
df.dtypes

accident_id            int64
city                     str
state                    str
latitude             float64
longitude            float64
date                     str
hour                   int64
day_of_week              str
is_weekend             int64
road_type                str
lanes                  int64
traffic_signal         int64
weather                  str
visibility               str
temperature            int64
traffic_density          str
cause                    str
accident_severity        str
vehicles_involved      int64
casualties             int64
is_peak_hour           int64
risk_score           float64
dtype: object

In [16]:
df["date"] =pd.to_datetime(df["date"],errors="coerce")

In [18]:
df["date"].dtype

dtype('<M8[us]')

In [20]:
df["date"].isnull().sum()

np.int64(0)

In [21]:
df["city"].unique()

<ArrowStringArray>
[      'Pune',     'Mumbai', 'Chandigarh',    'Chennai',      'Delhi',
  'Bangalore',  'Hyderabad',    'Kolkata']
Length: 8, dtype: str

In [23]:
df["state"].unique()

<ArrowStringArray>
['Maharashtra',      'Punjab',  'Tamil Nadu',       'Delhi',   'Karnataka',
   'Telangana', 'West Bengal']
Length: 7, dtype: str

In [25]:
df["weather"].unique()

<ArrowStringArray>
['fog', 'clear', 'rain']
Length: 3, dtype: str

In [27]:
df["cause"].unique()

<ArrowStringArray>
['weather', 'distraction', 'overspeeding', 'drunk driving', 'poor road']
Length: 5, dtype: str

In [29]:
df['accident_severity'].unique()

<ArrowStringArray>
['fatal', 'major', 'minor']
Length: 3, dtype: str

In [30]:
cat_cols = df.select_dtypes(include="str").columns

for col in cat_cols:
    print(f"\n---{col}---")
    print(df[col].unique())

---city---
<ArrowStringArray>
[      'Pune',     'Mumbai', 'Chandigarh',    'Chennai',      'Delhi',
  'Bangalore',  'Hyderabad',    'Kolkata']
Length: 8, dtype: str

---state---
<ArrowStringArray>
['Maharashtra',      'Punjab',  'Tamil Nadu',       'Delhi',   'Karnataka',
   'Telangana', 'West Bengal']
Length: 7, dtype: str

---day_of_week---
<ArrowStringArray>
['Sunday', 'Wednesday', 'Thursday', 'Monday', 'Friday', 'Tuesday', 'Saturday']
Length: 7, dtype: str

---road_type---
<ArrowStringArray>
['highway', 'urban', 'rural']
Length: 3, dtype: str

---weather---
<ArrowStringArray>
['fog', 'clear', 'rain']
Length: 3, dtype: str

---visibility---
<ArrowStringArray>
['low', 'high', 'medium']
Length: 3, dtype: str

---traffic_density---
<ArrowStringArray>
['high', 'low', 'medium']
Length: 3, dtype: str

---cause---
<ArrowStringArray>
['weather', 'distraction', 'overspeeding', 'drunk driving', 'poor road']
Length: 5, dtype: str

---accident_severity---
<ArrowStringArray>
['fatal', 'major', 'minor']
Length: 3, dtype: str

In [32]:
df.isnull().sum()

accident_id          0
city                 0
state                0
latitude             0
longitude            0
date                 0
hour                 0
day_of_week          0
is_weekend           0
road_type            0
lanes                0
traffic_signal       0
weather              0
visibility           0
temperature          0
traffic_density      0
cause                0
accident_severity    0
vehicles_involved    0
casualties           0
is_peak_hour         0
risk_score           0
dtype: int64

In [34]:
cat_cols =df.select_dtypes(include="str").columns

for  col  in  cat_cols:
    print(f"\n---{col}---")
    print(df[col].value_counts)

---city---
<bound method IndexOpsMixin.value_counts of 0              Pune
1            Mumbai
2            Mumbai
3        Chandigarh
4           Chennai
            ...
19995     Bangalore
19996       Chennai
19997       Chennai
19998       Kolkata
19999         Delhi
Name: city, Length: 20000, dtype: str>

---state---
<bound method IndexOpsMixin.value_counts of 0        Maharashtra
1        Maharashtra
2        Maharashtra
3             Punjab
4         Tamil Nadu
            ...
19995      Karnataka
19996     Tamil Nadu
19997     Tamil Nadu
19998    West Bengal
19999          Delhi
Name: state, Length: 20000, dtype: str>

---day_of_week---
<bound method IndexOpsMixin.value_counts of 0           Sunday
1           Sunday
2        Wednesday
3           Sunday
4         Thursday
           ...
19995     Thursday
19996     Saturday
19997     Saturday
19998       Sunday
19999       Friday
Name: day_of_week, Length: 20000, dtype: str>

---road_type---
<bound method IndexOpsMixin.value_counts of 0        highway
1          urban
2          urban
3          urban
4        highway
          ...
19995      urban
19996      urban
19997      rural
19998    highway
19999    highway
Name: road_type, Length: 20000, dtype: str>

---weather---
<bound method IndexOpsMixin.value_counts of 0          fog
1        clear
2          fog
3          fog
4        clear
         ...
19995    clear
19996    clear
19997    clear
19998    clear
19999     rain
Name: weather, Length: 20000, dtype: str>

---visibility---
<bound method IndexOpsMixin.value_counts of 0         low
1        high
2         low
3         low
4        high
         ...
19995    high
19996    high
19997    high
19998    high
19999     low
Name: visibility, Length: 20000, dtype: str>

---traffic_density---
<bound method IndexOpsMixin.value_counts of 0          high
1           low
2        medium
3          high
4           low
          ...
19995       low
19996       low
19997       low
19998       low
19999      high
Name: traffic_density, Length: 20000, dtype: str>

---cause---
<bound method IndexOpsMixin.value_counts of 0             weather
1             weather
2             weather
3         distraction
4         distraction
             ...
19995     distraction
19996     distraction
19997         weather
19998       poor road
19999    overspeeding
Name: cause, Length: 20000, dtype: str>

---accident_severity---
<bound method IndexOpsMixin.value_counts of 0        fatal
1        major
2        minor
3        minor
4        minor
         ...
19995    minor
19996    major
19997    minor
19998    minor
19999    minor
Name: accident_severity, Length: 20000, dtype: str>

In [36]:
df[cat_cols].nunique()

city                 8
state                7
day_of_week          7
road_type            3
weather              3
visibility           3
traffic_density      3
cause                5
accident_severity    3
dtype: int64

In [38]:
num_col =df.select_dtypes(include=["int64","float64"]).columns

num_col

Index(['accident_id', 'latitude', 'longitude', 'hour', 'is_weekend', 'lanes',
       'traffic_signal', 'temperature', 'vehicles_involved', 'casualties',
       'is_peak_hour', 'risk_score'],
      dtype='str')

In [40]:
df[num_col].describe().T

,count,mean,std,min,25%,50%,75%,max
accident_id,20000.0,9999.500000,5773.647028,0.000000,4999.750000,9999.500000,14999.250000,19999.000000
latitude,20000.0,20.389207,6.165791,12.800172,13.198653,18.812008,28.402467,30.799960
longitude,20000.0,78.173330,4.485967,72.700017,73.997979,77.297000,80.111089,88.499861
hour,20000.0,11.487200,6.945563,0.000000,5.000000,12.000000,18.000000,23.000000
is_weekend,20000.0,0.286150,0.451972,0.000000,0.000000,0.000000,1.000000,1.000000
lanes,20000.0,3.493950,1.705406,1.000000,2.000000,4.000000,5.000000,6.000000
traffic_signal,20000.0,0.499850,0.500012,0.000000,0.000000,0.000000,1.000000,1.000000
temperature,20000.0,27.579600,7.454746,15.000000,21.000000,28.000000,34.000000,40.000000
vehicles_involved,20000.0,2.992000,1.415534,1.000000,2.000000,3.000000,4.000000,5.000000
casualties,20000.0,1.726450,1.489104,0.000000,1.000000,1.000000,3.000000,5.000000
is_peak_hour,20000.0,0.247400,0.431512,0.000000,0.000000,0.000000,0.000000,1.000000
risk_score,20000.0,0.437585,0.218130,0.100000,0.250000,0.450000,0.600000,1.000000

In [41]:
for col  in num_col:
    print(f"{col}")

    print("negative :",(df[col] < 0 ).sum())
    print("Zero :",(df[col] == 0).sum() )

accident_id
negative : 0
Zero : 1
latitude
negative : 0
Zero : 0
longitude
negative : 0
Zero : 0
hour
negative : 0
Zero : 840
is_weekend
negative : 0
Zero : 14277
lanes
negative : 0
Zero : 0
traffic_signal
negative : 0
Zero : 10003
temperature
negative : 0
Zero : 0
vehicles_involved
negative : 0
Zero : 0
casualties
negative : 0
Zero : 4925
is_peak_hour
negative : 0
Zero : 15052
risk_score
negative : 0
Zero : 0

In [46]:
df.isnull().sum()

accident_id          0
city                 0
state                0
latitude             0
longitude            0
date                 0
hour                 0
day_of_week          0
is_weekend           0
road_type            0
lanes                0
traffic_signal       0
weather              0
visibility           0
temperature          0
traffic_density      0
cause                0
accident_severity    0
vehicles_involved    0
casualties           0
is_peak_hour         0
risk_score           0
dtype: int64

In [48]:
df.duplicated().sum()

np.int64(0)

In [50]:
df.shape

(20000, 22)

In [51]:
df.dtypes

accident_id                   int64
city                            str
state                           str
latitude                    float64
longitude                   float64
date                 datetime64[us]
hour                          int64
day_of_week                     str
is_weekend                    int64
road_type                       str
lanes                         int64
traffic_signal                int64
weather                         str
visibility                      str
temperature                   int64
traffic_density                 str
cause                           str
accident_severity               str
vehicles_involved             int64
casualties                    int64
is_peak_hour                  int64
risk_score                  float64
dtype: object

In [52]:
df.to_csv("Road_Accident_clean.csv",index=False)